const Router = require('express')
const router = new Router()
const deviceRouter = require('./deviceRouter')
const userRouter = require('./userRouter')
const brandRouter = require('./brandRouter')
const typeRouter = require('./typeRouter')
const basketRouter = require('./basketRouter')
const contactRouter = require('./contactRouter')
const orderRouter = require('./orderRouter')
const reviewRouter = require('./reviewRouter')
const searchRouter = require('./searchRouter')
const mailRouter = require('./mailRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/brand', brandRouter)
router.use('/device', deviceRouter)
router.use('/basket', basketRouter)
router.use('/contact', contactRouter)
router.use('/basket/order', orderRouter)
router.use('/', reviewRouter)
router.use('/search', searchRouter)
router.use('/faq', mailRouter)
module.exports = router